### ISSUE TITLE
PHP ^5.3.2 compatible version?

### ISSUE THREAD

**Issue by andrerom** [composer/package-versions-deprecated#4]
As Composer 2.x aims to support PHP 5.3 and higher, there needs to be a version of this package that support those PHP ^5.3.2 versions as well _if_ we want reach those users. 

Current code here is requiring `"php": "^7"`.

**Comment by nicolas-grekas** [comment]
No version of `Ocramius/PackageVersions` ever supported PHP < 7.
Since this package aims to "replace" it, there's no point IMHO to this request: projects that want to support PHP 5.3 and also want to get access to versions info should use the `Composer\InstalledVersions` class provided by Composer 2 instead.

**Comment by andrerom** [comment]
It seems you are correct ;)
_(it was provided as dev-master for older PHP versions for a while, but it seems we never used that on the branches we have that needs to support PHP 5.6 still)_
